version: "3.3"
services:
  jackett:    
    image: linuxserver/jackett    
    container_name: jackett
    environment:    
        - PUID=1000    
        - PGID=1000    
        - TZ=Americas/New_York
    volumes:    
        - ./config/jackett:/config
    ports:    
        - 9117:9117    
    restart: unless-stopped

  sonarr:
    build: ./sonarr
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York
    volumes:
        - ./config/sonarr:/config
        - ./media-server:/media-server
        - ./config/rclone:/config/rclone
        - ./scripts/sonarr:/scripts
    ports:
        - 8989:8989     
    depends_on:
        - jackett
    restart: unless-stopped
  
  radarr:
    build: ./radarr
    image: linuxserver/radarr
    container_name: radarr
    hostname: radarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York
    volumes:
        - ./config/radarr:/config
        - ./media-server:/media-server
        - ./config/rclone:/config/rclone
        - ./scripts/radarr:/scripts
    ports:
        - 7878:7878
    depends_on:
        - jackett
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    volumes:
        - ./media-server/media:/media
        - ./config/plex:/config
    environment:
        - PUID=1000
        - PGID=1000
        - version=docker
        - NVIDIA_VISIBLE_DEVICES=all
    ports:
        - 32400:32400
    restart: unless-stopped

  rdtclient:
      image: rogerfar/rdtclient
      container_name: rdtclient
      volumes:
          - './media-server/downloads:/data/downloads'
          - './media-server/db:/data/db'
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York
      restart: always
      logging:
          driver: json-file
          options:
              max-size: 10m
      ports:
          - '6500:6500'