version: "3.3"
services:
  jackett:    
    image: linuxserver/jackett    
    container_name: jackett
    env_file: .env
    volumes:    
        - ./config/jackett:/config
    ports:    
        - ${JACKETT_PORT}:${JACKETT_PORT}    
    restart: unless-stopped

  sonarr:
    build:
        context: ./sonarr
        args:
            USE_SONARR_EXTRA_BUILD_FILE: ${USE_SONARR_EXTRA_BUILD_FILE}
            SONARR_EXTRA_BUILD_FILE: ${SONARR_EXTRA_BUILD_FILE}
    image: linuxserver/sonarr
    container_name: sonarr
    env_file: .env
    volumes:
        - ./config/sonarr:/config
        - ${MEDIA_SERVER_PATH}:/media-server
        - ./config/rclone:/config/rclone
        - ./scripts/sonarr:/scripts
    ports:
        - ${SONARR_PORT}:${SONARR_PORT}
    depends_on:
        - jackett
    restart: unless-stopped
  
  radarr:
    build:
        context: ./radarr
        args:
            USE_RADARR_EXTRA_BUILD_FILE: ${USE_RADARR_EXTRA_BUILD_FILE}
            RADARR_EXTRA_BUILD_FILE: ${RADARR_EXTRA_BUILD_FILE}
    image: linuxserver/radarr
    container_name: radarr
    env_file: .env
    volumes:
        - ./config/radarr:/config
        - ${MEDIA_SERVER_PATH}:/media-server
        - ./config/rclone:/config/rclone
        - ./scripts/radarr:/scripts
    ports:
        - ${RADARR_PORT}:${RADARR_PORT}
    depends_on:
        - jackett
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    volumes:
        - ${MEDIA_SERVER_PATH}/media:/media
        - ./config/plex:/config
    env_file: .env
    ports:
        - ${PLEX_PORT}:${PLEX_PORT}
    restart: unless-stopped

  rdtclient:
      image: rogerfar/rdtclient
      container_name: rdtclient
      volumes:
          - "${MEDIA_SERVER_PATH}/downloads:/data/downloads"
          - "${MEDIA_SERVER_PATH}/db:/data/db"
      env_file: .env
      restart: always
      logging:
          driver: json-file
          options:
              max-size: 10m
      ports:
          - ${RDTCLIENT_PORT}:${RDTCLIENT_PORT}